# Generated by Django 5.2.11 on 2026-02-22 00:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('solution_overview', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tag')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', through='portfolio.ProjectTagMap', to='common.tag'),
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.technology')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', through='portfolio.ProjectTechnology', to='portfolio.technology'),
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PDF', 'PDF')], default='IMAGE', max_length=10)),
                ('file_url', models.URLField(max_length=1024)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'display_order'], name='idx_pm_project_order'), models.Index(fields=['project'], name='idx_pm_project')],
            },
        ),
        migrations.AddIndex(
            model_name='projecttagmap',
            index=models.Index(fields=['tag'], name='idx_prtm_tag'),
        ),
        migrations.AddConstraint(
            model_name='projecttagmap',
            constraint=models.UniqueConstraint(fields=('project', 'tag'), name='uq_project_tag'),
        ),
        migrations.AddIndex(
            model_name='projecttechnology',
            index=models.Index(fields=['technology'], name='idx_pt_technology'),
        ),
        migrations.AddConstraint(
            model_name='projecttechnology',
            constraint=models.UniqueConstraint(fields=('project', 'technology'), name='uq_project_technology'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'published_at'], name='idx_project_status_pub'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured', 'published_at'], name='idx_project_featured'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='idx_project_created'),
        ),
    ]
