# Generated by Django 5.2.11 on 2026-02-22 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80)),
                ('scope', models.CharField(choices=[('POST', 'Post'), ('PROJECT', 'Project'), ('ASSET', 'Asset')], max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['scope'], name='idx_tag_scope')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'slug'), name='uq_tag_scope_slug')],
            },
        ),
    ]
