# Generated by Django 5.2.11 on 2026-02-22 00:16

import booking.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
                ('slot_granularity_minutes', models.PositiveIntegerField(default=30)),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0)),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0)),
                ('max_bookings_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('min_lead_time_minutes', models.PositiveIntegerField(default=720)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['day_of_week', 'is_active'], name='idx_ar_day_active'), models.Index(fields=['timezone'], name='idx_ar_tz')],
            },
        ),
        migrations.CreateModel(
            name='ConsultingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('deliverables', models.JSONField(blank=True, null=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('allowed_durations_minutes', models.JSONField(blank=True, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('meeting_modes', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='idx_cs_status')],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('public_id', models.CharField(default=booking.models.generate_public_id, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED_BY_REQUESTER', 'Cancelled by requester'), ('CANCELLED_BY_ADMIN', 'Cancelled by admin'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=30)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('requested_start_at', models.DateTimeField()),
                ('requested_end_at', models.DateTimeField()),
                ('meeting_mode', models.CharField(choices=[('GOOGLE_MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('PHONE', 'Phone'), ('IN_PERSON', 'In-person')], max_length=20)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.consultingservice')),
            ],
        ),
        migrations.CreateModel(
            name='BlackoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['start_at', 'end_at'], name='idx_blackout_range')],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('RELEASED', 'Released')], default='CONFIRMED', max_length=12)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='booking.bookingrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'start_at'], name='idx_bs_status_start'), models.Index(fields=['start_at', 'end_at'], name='idx_bs_range')],
            },
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['service', 'status', 'requested_start_at'], name='idx_br_svc_status_time'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['email', 'created_at'], name='idx_br_email_created'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'requested_start_at'], name='idx_br_status_time'),
        ),
    ]
