# Generated by Django 5.2.11 on 2026-02-22 00:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('TOOL', 'Tool'), ('TEMPLATE', 'Template'), ('GUIDE', 'Guide'), ('LINK', 'Link')], max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('COMING_SOON', 'Coming soon'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('external_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('download_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.tag')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', through='assets.AssetTagMap', to='common.tag'),
        ),
        migrations.AddIndex(
            model_name='assettagmap',
            index=models.Index(fields=['tag'], name='idx_atm_tag'),
        ),
        migrations.AddConstraint(
            model_name='assettagmap',
            constraint=models.UniqueConstraint(fields=('asset', 'tag'), name='uq_asset_tag'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'published_at'], name='idx_asset_status_pub'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='idx_asset_type'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_featured', 'published_at'], name='idx_asset_featured'),
        ),
    ]
